body:
  - type: input
    id: livewire-version
    attributes:
      label: Livewire version
      description: Which version of Livewire are you using? Please provide the full version, e.g. v4.2.4.
      placeholder: v4.2.4
    validations:
      required: true

  - type: input
    id: laravel-version
    attributes:
      label: Laravel version
      description: Which version of Laravel are you using? Please provide the full version, e.g. v13.0.0.
      placeholder: v13.0.0
    validations:
      required: true

  - type: input
    id: php-version
    attributes:
      label: PHP version
      description: Which version of PHP are you using? Please provide the full version, e.g. 8.5.5.
      placeholder: "8.5.5"
    validations:
      required: true

  - type: input
    id: browser-os
    attributes:
      label: Browser and operating system
      description: Which browser and operating system are you using?
      placeholder: Chrome on macOS
    validations:
      required: true

  - type: textarea
    attributes:
      label: What do you need help with?
      description: Please provide a clear description of what you need help with, along with code snippets (ideally a Livewire single-file component) and screenshots or screen recordings if they help illustrate your issue.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Include code snippets in triple backticks (\```) with "blade" or "php" for better readability. Here's an example:

        \```blade
        // Your code here
        \```

        \```php
        // Your code here
        \```

  - type: textarea
    attributes:
      label: How do you expect it to work?
      description: Please describe how you expect it to work.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Please confirm
      options:
        - label: I have searched existing discussions to check this hasn't already been answered.
          required: true
        - label: I have provided code samples as text and NOT images.
          required: true
