name: Bug report
description: File a report for a bug in Livewire.
body:
  - type: markdown
    attributes:
      value: |
        Hi there! 👋

        Thank you for using Livewire!

        Many of the people who help resolve issues here are enthusiastic Livewire users like yourself who volunteer their time to support fellow community members.

        **To respect everyone's valuable time and help you resolve your issue as quickly as possible, before posting an issue, please**

        * Update to the latest version of Livewire by running `composer update livewire/livewire`
        * Clear the view cache by running `php artisan view:clear`
        * Make sure you have thoroughly **searched all open and closed Issues and Discussions** to make sure your question/issue has not already been answered

  - type: input
    id: livewire-version
    attributes:
      label: Livewire version
      description: Which version of Livewire are you using? Please provide the full version, e.g. v3.5.16.
      placeholder: v3.5.16
    validations:
      required: true

  - type: input
    id: browser-os
    attributes:
      label: Browser and Operating System
      description: Which browser and operating system are you using?
      placeholder: Chrome on macOS
    validations:
      required: true

  - type: textarea
    attributes:
      label: What is the problem?
      description: Please provide a clear and concise description of what the problem is and include screenshots.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Code snippets
      description: Please include a code snippet (ideally a Volt component) we can copy and paste into our own apps with steps to reproduce. Be sure to **include any Blade variable definitions** that are used and use as little code as possible to reproduce the issue.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Include code snippets in triple backticks (\```) with "blade" for better readability. Here's an example:

        \```blade
        // Your code here
        \```

  - type: textarea
    attributes:
      label: How do you expect it to work?
      description: Please describe how you expect it to work.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **We will close this issue for any of the following reasons**

        * The code snippets contain unrelated code and/or external dependencies such as left-over Blade variables or Models
        * We cannot reproduce the issue with the provided code snippets
        * The issue is a duplicate

  - type: checkboxes
    attributes:
      label: Please confirm (incomplete submissions will not be addressed)
      options:
        - label: I have provided easy and step-by-step instructions to reproduce the bug.
          required: true
        - label: I have provided code samples as text and NOT images.
          required: true
        - label: I understand my bug report will be closed if I haven't met the criteria above.
          required: true

  - type: markdown
    attributes:
      value: Thank you!